apiVersion: v1
kind: ConfigMap
metadata:
  name: file-storage-config
  namespace: vextrus
data:
  NODE_ENV: "production"
  PORT: "3004"
  DATABASE_HOST: "postgres.vextrus.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "vextrus_erp"
  REDIS_HOST: "redis.vextrus.svc.cluster.local"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "minio.vextrus.svc.cluster.local"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET_NAME: "vextrus-files"
  MAX_FILE_SIZE: "104857600"  # 100MB
  ALLOWED_FILE_TYPES: "pdf,doc,docx,xls,xlsx,png,jpg,jpeg,gif,zip,rar"
  VIRUS_SCAN_ENABLED: "true"
  CLAMAV_HOST: "clamav.vextrus.svc.cluster.local"
  CLAMAV_PORT: "3310"
  THUMBNAIL_GENERATION: "true"
  THUMBNAIL_SIZE: "200x200"
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"