apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-database-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ include "vextrus-erp.databaseUrl" . }}
  host: {{ .Release.Name }}-postgresql
  port: "5432"
  database: {{ .Values.postgresql.auth.database }}
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ include "vextrus-erp.redisUrl" . }}
  host: {{ .Release.Name }}-redis-master
  port: "6379"
  {{- if .Values.redis.auth.enabled }}
  password: {{ .Values.redis.auth.password }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.services.auth.jwt.secret | default (randAlphaNum 32) }}
  expiresIn: {{ .Values.services.auth.jwt.expiresIn }}
---
{{- if .Values.services.notification.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-smtp-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.services.notification.smtp.host }}
  port: {{ .Values.services.notification.smtp.port | quote }}
  user: {{ .Values.services.notification.smtp.auth.user }}
  pass: {{ .Values.services.notification.smtp.auth.pass }}
{{- end }}
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-minio-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  endpoint: {{ .Release.Name }}-minio:9000
  accessKey: {{ .Values.minio.auth.rootUser }}
  secretKey: {{ .Values.minio.auth.rootPassword }}
{{- end }}
---
{{- if .Values.temporal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vextrus-erp.fullname" . }}-temporal-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vextrus-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Release.Name }}-temporal
  port: "7233"
  namespace: {{ .Values.services.workflow.temporal.namespace }}
  taskQueue: {{ .Values.services.workflow.temporal.taskQueue }}
{{- end }}