apiVersion: v2
name: vextrus-erp
description: Enterprise ERP System for Bangladesh Construction & Real Estate
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - erp
  - construction
  - real-estate
  - bangladesh
home: https://github.com/vextrus/vextrus-erp
sources:
  - https://github.com/vextrus/vextrus-erp
maintainers:
  - name: Vextrus Team
    email: team@vextrus.com
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 26.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/vextrus/vextrus-erp/docs
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"