apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: vextrus
  labels:
    app: temporal
    component: infrastructure
    tier: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
        component: infrastructure
        tier: orchestration
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.22.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7233
          name: grpc
          protocol: TCP
        - containerPort: 7234
          name: membership
          protocol: TCP
        - containerPort: 7235
          name: history
          protocol: TCP
        - containerPort: 7239
          name: matching
          protocol: TCP
        - containerPort: 6933
          name: frontend
          protocol: TCP
        - containerPort: 6934
          name: worker
          protocol: TCP
        env:
        - name: DB
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: POSTGRES_SEEDS
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: host
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: /etc/temporal/config/dynamicconfig/development.yaml
        - name: ENABLE_ES
          value: "false"
        - name: ES_SCHEME
          value: "http"
        - name: ES_SEEDS
          value: "elasticsearch"
        - name: ES_PORT
          value: "9200"
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - temporal
            - operator
            - cluster
            - health
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - temporal
            - operator
            - cluster
            - health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: dynamic-config
          mountPath: /etc/temporal/config/dynamicconfig
          readOnly: true
      volumes:
      - name: dynamic-config
        configMap:
          name: temporal-dynamic-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: vextrus
  labels:
    app: temporal-ui
    component: ui
    tier: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
        component: ui
        tier: orchestration
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:2.21.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: TEMPORAL_ADDRESS
          value: temporal:7233
        - name: TEMPORAL_CORS_ORIGINS
          value: http://localhost:3000,http://localhost:4000,https://api.vextrus.com
        - name: TEMPORAL_DEFAULT_NAMESPACE
          value: vextrus
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3