# Simplified OpenTelemetry Collector Configuration
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:*"
            - "http://api.localhost:*"

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 70

exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 100

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: vextrus
    const_labels:
      environment: development

  otlphttp:
    endpoint: http://localhost:4318
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/health"

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]