version: '3.8'

services:
  # Core infrastructure (already running)
  postgres:
    image: postgres:16-alpine
    container_name: vextrus-postgres
    environment:
      POSTGRES_USER: vextrus
      POSTGRES_PASSWORD: vextrus_dev_2024
      POSTGRES_DB: vextrus_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vextrus-network

  redis:
    image: redis:7-alpine
    container_name: vextrus-redis
    command: redis-server --appendonly yes --requirepass vextrus_redis_2024
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vextrus-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: vextrus-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vextrus-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: vextrus-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - vextrus-network

  # Build just auth service first as a test
  auth:
    build:
      context: .
      dockerfile: ./infrastructure/docker/services/final.Dockerfile
      args:
        SERVICE_NAME: "@vextrus/auth-service"
        SERVICE_PATH: services/auth
        SERVICE_PORT: 3001
    container_name: vextrus-auth
    environment:
      NODE_ENV: development
      APP_PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vextrus
      DATABASE_PASSWORD: vextrus_dev_2024
      DATABASE_NAME: vextrus_erp
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: vextrus_redis_2024
      KAFKA_BROKERS: kafka:9093
      JWT_ACCESS_SECRET: vextrus_jwt_access_secret_dev_2024
      JWT_REFRESH_SECRET: vextrus_jwt_refresh_secret_dev_2024
    ports:
      - "3001:3001"
    networks:
      - vextrus-network
    depends_on:
      - postgres
      - redis
      - kafka

networks:
  vextrus-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  zookeeper_data: