global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vextrus-monitor'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert-rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
        labels:
          service: 'otel-collector'

  # Node.js services metrics
  - job_name: 'nodejs-services'
    static_configs:
      - targets:
          - 'auth:3001'
          - 'master-data:3002'
          - 'workflow:3011'
          - 'rules-engine:3012'
          - 'api-gateway:4000'
        labels:
          service_type: 'nodejs'
    metrics_path: '/metrics'

  # Infrastructure services metrics
  - job_name: 'infrastructure-services'
    static_configs:
      - targets:
          - 'audit:3009'
          - 'notification:3003'
          - 'file-storage:3004'
          - 'document-generator:3008'
          - 'scheduler:3005'
          - 'configuration:3007'
          - 'import-export:3010'
        labels:
          service_type: 'infrastructure'
    metrics_path: '/metrics'

  # PostgreSQL metrics (using postgres_exporter if deployed)
  - job_name: 'postgresql'
    static_configs:
      - targets: []
        # - postgres-exporter:9187
        labels:
          service: 'postgresql'

  # Redis metrics (using redis_exporter if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: []
        # - redis-exporter:9121
        labels:
          service: 'redis'

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
        labels:
          service: 'kafka'

  # Temporal metrics
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:9090']
        labels:
          service: 'temporal'

  # Docker metrics (if cadvisor is deployed)
  - job_name: 'docker'
    static_configs:
      - targets: []
        # - cadvisor:8080
        labels:
          service: 'docker'

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
        labels:
          service: 'traefik'
    metrics_path: '/metrics'