apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service-staging
  namespace: vextrus-staging
  labels:
    app: finance-service
    environment: staging
    version: week1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-service
      environment: staging
  template:
    metadata:
      labels:
        app: finance-service
        environment: staging
        version: week1
    spec:
      containers:
      - name: finance-service
        image: vextrus/finance:week1-staging
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3014
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "staging"
        - name: PORT
          value: "3014"
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: finance-db-staging
              key: host
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-db-staging
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-db-staging
              key: password
        - name: DATABASE_NAME
          value: "vextrus_finance_staging"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finance-secrets-staging
              key: jwt-secret
        - name: CORS_ORIGIN
          value: "https://staging.vextrus.com,https://staging-app.vextrus.com"
        - name: EVENTSTORE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: finance-secrets-staging
              key: eventstore-connection
        - name: KAFKA_BROKERS
          value: "kafka-staging:9092"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz-staging:4318"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3014
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3014
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service-staging
  namespace: vextrus-staging
  labels:
    app: finance-service
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: finance-service
    environment: staging
  ports:
  - name: http
    port: 80
    targetPort: 3014
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-service-staging-config
  namespace: vextrus-staging
data:
  LOG_LEVEL: "debug"
  ENABLE_SWAGGER: "true"
  ENABLE_INTROSPECTION: "true"
