---
# Production Stable Deployment (70% traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service-stable
  namespace: vextrus-production
  labels:
    app: finance-service
    environment: production
    version: stable
spec:
  replicas: 7  # 70% of total capacity (7 out of 10 pods)
  selector:
    matchLabels:
      app: finance-service
      environment: production
      track: stable
  template:
    metadata:
      labels:
        app: finance-service
        environment: production
        track: stable
        version: stable
    spec:
      containers:
      - name: finance-service
        image: vextrus/finance:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 3014
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3014"
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: host
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: password
        - name: DATABASE_NAME
          value: "vextrus_finance"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: jwt-secret
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: cors-origin
        - name: EVENTSTORE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: eventstore-connection
        - name: KAFKA_BROKERS
          value: "kafka-production-0:9092,kafka-production-1:9092,kafka-production-2:9092"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz:4318"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3014
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3014
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
# Week 2 Canary Deployment (30% traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service-week2
  namespace: vextrus-production
  labels:
    app: finance-service
    environment: production
    version: week2
    security-fixes: "eval-csrf-cors-credentials"
spec:
  replicas: 3  # 30% of total capacity (3 out of 10 pods)
  selector:
    matchLabels:
      app: finance-service
      environment: production
      track: canary
  template:
    metadata:
      labels:
        app: finance-service
        environment: production
        track: canary
        version: week2
      annotations:
        security-fixes: "eval-code-injection,csrf-protection,cors-strict,credentials-removed"
        deployment-date: "2025-10-16"
        rollout-percentage: "30"
        previous-version: "week1"
    spec:
      containers:
      - name: finance-service
        image: vextrus/finance:week2-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 3014
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3014"
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: host
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-db-production
              key: password
        - name: DATABASE_NAME
          value: "vextrus_finance"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: jwt-secret
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: cors-origin
        - name: EVENTSTORE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: finance-secrets-production
              key: eventstore-connection
        - name: KAFKA_BROKERS
          value: "kafka-production-0:9092,kafka-production-1:9092,kafka-production-2:9092"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz:4318"
        # Canary-specific tags for monitoring
        - name: DEPLOYMENT_TRACK
          value: "canary"
        - name: DEPLOYMENT_VERSION
          value: "week2"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3014
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3014
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
# Service (unchanged - load balances across both stable and canary)
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: vextrus-production
  labels:
    app: finance-service
    environment: production
spec:
  type: ClusterIP
  selector:
    app: finance-service
    environment: production
  ports:
  - name: http
    port: 80
    targetPort: 3014
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
# Horizontal Pod Autoscaler for Week 2 Canary
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finance-service-week2-hpa
  namespace: vextrus-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finance-service-week2
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
