apiVersion: v1
kind: Service
metadata:
  name: master-data-service
  namespace: vextrus
  labels:
    app: master-data
    component: backend
    tier: business
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
spec:
  type: ClusterIP
  selector:
    app: master-data
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  - port: 9464
    targetPort: 9464
    protocol: TCP
    name: metrics
  sessionAffinity: None