apiVersion: v1
kind: Service
metadata:
  name: rules-engine-service
  namespace: vextrus
  labels:
    app: rules-engine
    component: backend
    tier: business
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3012"
spec:
  type: ClusterIP
  selector:
    app: rules-engine
  ports:
  - port: 3012
    targetPort: 3012
    protocol: TCP
    name: http
  - port: 9464
    targetPort: 9464
    protocol: TCP
    name: metrics
  sessionAffinity: None