apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: vextrus
  labels:
    app: workflow
    component: backend
    tier: orchestration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3011"
spec:
  type: ClusterIP
  selector:
    app: workflow
  ports:
  - port: 3011
    targetPort: 3011
    protocol: TCP
    name: http
  - port: 9464
    targetPort: 9464
    protocol: TCP
    name: metrics
  sessionAffinity: None